In [1]:
import numpy as np

In [2]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # Features ( Hrs Slept, Hrs Studied)
y = np.array(([92], [86], [89]), dtype=float)# Labels(Marks obtained)
X = X/np.amax(X,axis=0) # Normalize
y = y/100

In [3]:
def sigmoid(x):
 return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
 return x * (1 - x)

In [4]:
# Variable initialization
epoch=1000 #Setting training iterations
eta =0.2 #Setting learning rate (eta)
input_neurons = 2 #number of features in data set
hidden_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [11]:
# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) # 2x3
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons)) # 1x3
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 1x1
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)

[[0.72418639 0.85017618 0.93380993]
 [0.80597813 0.5384786  0.4046206 ]]
[[0.38502327 0.42029895 0.97967123]]
[[0.80487636]
 [0.45630989]
 [0.76021439]]
[[0.78949729]]


In [6]:
for i in range(epoch):
#Forward Propogation
 h_ip=np.dot(X,wh) + bh # Dot product + bias
 h_act = sigmoid(h_ip) # Activation function
 o_ip=np.dot(h_act,wout) + bout
 output = sigmoid(o_ip)

In [8]:
#Backpropagation
 # Error at Output layer
Eo = y-output # Error at o/p
outgrad = sigmoid_grad(output)
d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)

In [14]:
# Error at Hidden later
Eh = d_output.dot(wout.T) # .T means transpose
hiddengrad = sigmoid_grad(h_act) # How much hidden layer wts contributed to error
d_hidden = Eh * hiddengrad
wout += h_act.T.dot(d_output) *eta # Dotproduct of nextlayererror and currentlayerop
wh += X.T.dot(d_hidden) *eta

In [13]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.81515798]
 [0.80396907]
 [0.81352198]]
